export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const UPDATE_SALES_INFO = "UPDATE_SALES_INFO";
export const UPDATE_PAYMENT_INFO = "UPDATE_PAYMENT_INFO";
export const UPDATE_SALES_NOTE = "UPDATE_SALES_NOTE";